### ISSUE TITLE
Status 정보가 나오지 않는 문제

### ISSUE THREAD

**Issue by daeinlee** [hackcatml/mlviewer#1]
어태치하면 앱은 실행되지만, Status 정보가 나오지 않고 status 버튼 누르면 이런 에러 메세지가 나옵니다!
Status 정보가 없어서 Offset 정보도 나오지 않네요. 
피온북, 크롬으로 테스트해봤습니다.

![Status](https://user-images.githubusercontent.com/34927021/215960511-4d479635-7f6a-429c-b39f-bd3d98ce8efb.png)

**Comment by hackcatml** [comment]
안녕하세요. 답변이 늦었네요. 이슈가 재현되지 않아 이슈 종료하고자 합니다.
최신 버전 git clone 해서 한번 해보시겠어요?

**Comment by daeinlee** [comment]
넵! 해보겠습니다. 감사합니다.

**Comment by daeinlee** [comment]
> Owner

이제 잘 됩니다. 좋은 도구 공유해 주셔서 고맙습니다! mlviewer 같은 것이 있으면 좋겠다라고 생각만 하고 있었는데, 너무 좋습니다! b
