### ISSUE TITLE
ImportError: DLL load failed while importing QtCore: 找不到指定的程序

### ISSUE THREAD

**Issue by 350030173** [hackcatml/mlviewer#2]
![1](https://github.com/hackcatml/mlviewer/assets/20263746/22bb4aac-7de9-43ae-ba92-e5108349d765)
![2](https://github.com/hackcatml/mlviewer/assets/20263746/7521c4e9-fadc-4d36-ab11-01f96fdffe14)

This error is reported even if the version of pyqt6 is as follows
PyQt6 = = 6.4.0
PyQt6 - Qt6 = = 6.4.1
PyQt6 - sip = = 13.4.0

**Comment by hackcatml** [comment]
Hello. I can't reproduce the issue on my Windows laptop.
Could you try with git cloning and python venv?

```
# Git clone
git clone https://github.com/hackcatml/mlviewer.git
cd mlviewer

# Create python virtual environment
python -m venv .\venv

# Activate python venv
venv\Scripts\activate.bat

# Install requirements
pip install -r requirments.txt

# Run
python main.py
```

By the way, It's confirmed that the 1.0.1 version I uploaded has broken UI on Windows.
I will update release soon, thanks.

**Comment by 350030173** [comment]
> Hello. I can't reproduce the issue on my Windows laptop. Could you try with git cloning and python venv?
> 
> ```
> # Git clone
> git clone https://github.com/hackcatml/mlviewer.git
> cd mlviewer
> 
> # Create python virtual environment
> python -m venv .\venv
> 
> # Activate python venv
> venv\Scripts\activate.bat
> 
> # Install requirements
> pip install -r requirments.txt
> 
> # Run
> python main.py
> ```
> 
> By the way, It's confirmed that the 1.0.1 version I uploaded has broken UI on Windows. I will update release soon, thanks.



Still the same error, may be my win7 environmental problems, but I use win10 is normal
