### ISSUE TITLE
특정 함수로 이동 시 violation accessing 문제

### ISSUE THREAD

**Issue by daeinlee** [hackcatml/mlviewer#3]
안녕하세요.  좋은 도구 만들어 주셔서 감사합니다.

malview에서 언리얼 4점대 엔진에서 
UFunction Invoke 함수의 offset 입력 시 violation accessing 문제가 나옵니다.
이 부분 접근할 수 있는 방법을 알 수 있을까요~?
![malview에러](https://github.com/hackcatml/mlviewer/assets/34927021/756f842c-e748-43f5-8519-82f99fb27754)

**Comment by hackcatml** [comment]
안녕하세요.
Offset 은 현재 모듈의 base 주소로부터의 offset 을 의미합니다.
올려주신 사진의 Name을 보니 현재 모듈이 app_process64 이군요.
Name 탭에서 우선 libUE4.so 를 입력 및 엔터키를 눌러 해당 모듈의 base 주소로 이동 후 Offset 입력 해보시기 바랍니다.

**Comment by daeinlee** [comment]
앗 감사합니다. 아래를 보고 해야 하는군요.
감사합니다! 해보겠습니다.

**Comment by daeinlee** [comment]
IOS에서 해봤는데, NAME이 바로 SO 파일로 설정되네요. 
감사합니다!
