### ISSUE TITLE
frida로 직접 접근한 주소의 값이 mlviewer와 값이 다른 문제

### ISSUE THREAD

**Issue by daeinlee** [hackcatml/mlviewer#4]
아래 사진은 제가 Frida(16.1.4)에서 X3(console.warn(hexdump(this.context.x3)))로 받는 포인터로 이동한 내용인데, 왼쪽은 제가 직접 frida에서 로깅한 내용이고 우측은 mlviewer로 접근한 사진인데 같은 주소인데 값이 다릅니다.

제가 궁금한 부분은 직접 frida로 로깅한 부분의 값이 맞다는 것은 아니고, 이런 일도 생길 수 있는 일인지 궁금합니다.

![frida와 비교](https://github.com/hackcatml/mlviewer/assets/34927021/1e5a1dea-56b3-4770-bc04-5c76f049fd5a)

**Comment by hackcatml** [comment]
mlviewer 로 Address 에 접근하면 현재 시점의 메모리 현황을 보여주는 것입니다.
올려주신 내용을 보니, Interceptor.attach 로 특정 주소를 후킹해서 onEnter 시점에 hexdump를 한 것으로 보이네요.
onLeave 시점에도 hexdump를 해보시기 바랍니다.
그리고 Intercept 하지 마시고, 직접 주소값에 대해 hexdump해보세요. (mlviewer 로 주소값으로 이동하는 것과 같음)
```
console.log(hexdump(ptr(0x16fe71440)))
```

**Comment by daeinlee** [comment]
답변 고맙습니다.
mlviewer에서 봤을 때는 이미 처리된 데이터라 값이 다른 것이 맞겠군요 ㅠㅠ
말씀주신 부분 확인해 보겠습니다.
